services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./backend:/app/backend
      - ./modules:/app/modules