services:

  ai:
    build:
      context: .
      dockerfile: ai/Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./ai:/app/ai
      - ./modules:/app/modules
      - ./models:/app/models
      - ./data:/app/data
    restart: unless-stopped
    stdin_open: true
    tty: true
    
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./modules:/app/modules
    restart: unless-stopped