apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-backend
  namespace: echo
  labels:
    app: echo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-backend
  template:
    metadata:
      labels:
        app: echo-backend
    spec:
      initContainers:
      - name: setup
        image: busybox
        command: ['sh', '-c', 'mkdir -p /app/vision/results']
        volumeMounts:
        - name: results
          mountPath: /app/vision/results
      containers:
      - name: backend
        image: vinbr/echo-backend:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: results
          mountPath: /app/vision/results
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
      volumes:
      - name: results
        emptyDir: {}
