apiVersion: v1
kind: Service
metadata:
  name: echo-frontend
  namespace: echo
spec:
  type: ClusterIP
  selector:
    app: echo-frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
