apiVersion: apps/v1
kind: Deployment
metadata:
  name: arc-vision
  namespace: arc
  labels:
    app: arc-vision
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arc-vision
  template:
    metadata:
      labels:
        app: arc-vision
    spec:
      containers:
      - name: vision
        image: vinbr/arc-vision:latest
        ports:
        - containerPort: 8001
        volumeMounts:
        - name: data
          mountPath: /app/data
        stdin: true
        tty: true
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: arc-data-pvc
